Adf Fix problem Task for Consult Beneficiaries
opensrp/opensrp-client-eusm pull request #120
Opened 2023-02-22 10:15 UTC by hamza-vd

Closes #116

2023-02-27 10:16 UTC, bennsimon requested changes

2023-02-27 10:16 UTC, bennsimon commented on opensrp-eusm/src/main/java/org/smartregister/eusm/viewholder/TaskRegisterViewHolder.java
> +            } else if (AppConstants.TaskCode.FIX_PROBLEM_CONSULT_BENEFICIARIES.equalsIgnoreCase(taskDetail.getTaskCode())) {
Whats the value of `taskDetail.getEntityName()` here? If its the same as taskCode kindly use the entityName.

2023-02-27 10:16 UTC, bennsimon commented on opensrp-eusm/src/main/java/org/smartregister/eusm/fragment/EusmTasksRegisterFragment.java
> +                    } else if (AppConstants.TaskCode.FIX_PROBLEM_CONSULT_BENEFICIARIES.equalsIgnoreCase(taskDetail.getTaskCode())) {
Whats the value of `taskDetail.getEntityName()` here? If its the same as taskCode kindly use the entityName.

2023-03-02 14:24 UTC, bennsimon requested changes

2023-03-02 14:24 UTC, bennsimon commented on opensrp-eusm/src/main/java/org/smartregister/eusm/util/AppJsonFormUtils.java
> +                    || (AppConstants.JsonForm.FIX_PROBLEM_FORM.equals(formName) && taskDetail.getTaskCode().equals(AppConstants.TaskCode.FIX_PROBLEM_CONSULT_BENEFICIARIES))) {
```suggestion
                    || (AppConstants.JsonForm.FIX_PROBLEM_FORM.equals(formName) && AppConstants.TaskCode.FIX_PROBLEM_CONSULT_BENEFICIARIES.equals(taskDetail.getTaskCode())) {
```

2023-03-02 14:24 UTC, bennsimon commented on opensrp-eusm/src/main/java/org/smartregister/eusm/util/AppJsonFormUtils.java
> +                    || (AppConstants.JsonForm.FIX_PROBLEM_FORM.equals(formName) && taskDetail.getTaskCode().equals(AppConstants.TaskCode.FIX_PROBLEM_CONSULT_BENEFICIARIES))) {
switch the equals arg.

2023-03-02 14:36 UTC, hamza-vd commented on opensrp-eusm/src/main/java/org/smartregister/eusm/util/AppJsonFormUtils.java
> +                    || (AppConstants.JsonForm.FIX_PROBLEM_FORM.equals(formName) && taskDetail.getTaskCode().equals(AppConstants.TaskCode.FIX_PROBLEM_CONSULT_BENEFICIARIES))) {
Done

2023-03-07 12:57 UTC, bennsimon approved these changes

2023-03-07 12:59 UTC, merged